import { Tile } from "@src/types/tiles";

export const testGrid: Tile[][] = [
    [
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: true,
            value: 0,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: true,
            value: 0,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
    ],
    [
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: true,
            value: 0,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: true,
            value: 0,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
    ],
    [
        {
            voltorb: false,
            value: 2,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: true,
            value: 0,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 3,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
    ],
    [
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 3,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
    ],
    [
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: true,
            value: 0,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 1,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
        {
            voltorb: false,
            value: 2,
            revealed: false,
            selected: false,
            marks: new Set(),
        },
    ],
];
